use_frameworks!

platform :ios, '9.0'

target 'KEPRequestCapture_Example' do
  pod 'KEPRequestCapture', :path => '../'

  target 'KEPRequestCapture_Tests' do
    inherit! :search_paths

    
  end
end
